db:
  image: mongo
  ports:
    - "27018:27017"
  # command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: node src/index.js
  volumes:
    - .:/src
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PORT: 3000
